-- Create clues table
CREATE TABLE IF NOT EXISTS clues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phase_number INTEGER NOT NULL,
  quest_number INTEGER NOT NULL,
  location_hint TEXT,
  clue_text TEXT NOT NULL,
  answer_code TEXT NOT NULL
);

-- Create participants table
CREATE TABLE IF NOT EXISTS participants (
  participant_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  roll_number TEXT,
  branch TEXT,
  current_phase INTEGER DEFAULT 1,
  current_quest_index INTEGER DEFAULT 1,
  letters_collected TEXT[] DEFAULT '{}',
  phase1_time TIMESTAMPTZ,
  phase2_time TIMESTAMPTZ,
  completion_time TIMESTAMPTZ,
  completion_duration INTEGER,
  is_phase1_winner BOOLEAN DEFAULT FALSE,
  is_phase2_winner BOOLEAN DEFAULT FALSE
);

-- Create game_state table
CREATE TABLE IF NOT EXISTS game_state (
  id INTEGER PRIMARY KEY DEFAULT 1,
  current_phase INTEGER DEFAULT 1,
  phase1_winner_declared BOOLEAN DEFAULT FALSE,
  phase2_winner_declared BOOLEAN DEFAULT FALSE,
  active_quest INTEGER DEFAULT 1,
  target_word TEXT
);

-- Insert initial game state
INSERT INTO game_state (id, current_phase, phase1_winner_declared, phase2_winner_declared, active_quest, target_word)
VALUES (1, 1, FALSE, FALSE, 1, 'I451S')
ON CONFLICT (id) DO UPDATE 
SET current_phase = 1, phase1_winner_declared = FALSE, phase2_winner_declared = FALSE, active_quest = 1, target_word = 'I451S';

-- Clear existing clues to avoid duplicates if re-running
TRUNCATE TABLE clues;

-- Populate Clues for Phase 1
INSERT INTO clues (phase_number, quest_number, clue_text, answer_code) VALUES
(1, 1, 'Where minds gather before they rise, Between floors and flowing ties. A place of pause before the climb, Look around — the answer waits in time.', 'I'),
(1, 2, 'From the home of ideas, start your walk, Toward the block where ''B'' leads the talk. As you take the turn, look straight once more, A giant wall stands guarding...', '4'),
(1, 3, 'The number four has shown the way, Now let your journey continue today. Leave B behind and move with glee, Find the small gate that welcomes P.', '5'),
(1, 4, 'From P your journey now must flow, Toward the spot where long chats grow. A new stall greets you on the way, But glance to the right — the answer will stay.', '1'),
(1, 5, 'Conversations done, move ahead with aim, Toward the block of talks, careers, and fame. Where banners dress the outer wall, The final mark awaits your call.', 'S');

-- Populate Clues for Phase 2
INSERT INTO clues (phase_number, quest_number, clue_text, answer_code) VALUES
(2, 1, 'Enter the land where thinkers roam, Beyond the gate of Azim’s home. A curved old stall now silent stays, Look nearby to begin the chase.', '7'),
(2, 2, 'Leave the curved silence behind your view, Walk ahead where the letter B calls you. At its gate where messages often stay, Between the pillars your next mark will lay.', 'H'),
(2, 3, 'From B continue your steady pace, Toward the block where P marks the place. Two paths of steps will split the way, One climbs high, one dips to stay. Choose the path that journeys down, Your next symbol waits around.', '3'),
(2, 4, 'Leave the steps of P behind, Walk the path where lights align. Toward the place where long nights grow, At its first walls the next sign will show.', 'N'),
(2, 5, 'Leave the halls of LP behind, Toward Raman where ambitions shine. Climb the steps where journeys rise, A waiting space before your eyes. Pause a moment, look once more — The final mark rests near the floor.', '4');

-- Enable Realtime
-- Note: This usually needs to be done via the Supabase Dashboard or a specific SQL command if the publication exists.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE participants;
    ALTER PUBLICATION supabase_realtime ADD TABLE game_state;
  END IF;
END $$;

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_clues_phase_quest ON clues (phase_number, quest_number);
CREATE INDEX IF NOT EXISTS idx_participants_current_phase ON participants (current_phase);
CREATE INDEX IF NOT EXISTS idx_participants_quest_index ON participants (current_quest_index);
CREATE INDEX IF NOT EXISTS idx_participants_completion_time ON participants (completion_time);
